1. Write a Python code to import NumPy.

In [2]:
import numpy as np

2. Write a Python program to create 3x3 matrix with values ranging from 5 to 13.

In [7]:
a = np.arange(5,14)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [15]:
b = np.zeros(10)
b[5] = 11
print(b)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to create a array with values ranging from 12 to 38.

In [20]:
c = np.arange(12,38).reshape(13,2)
print(c)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]]


6. Write a Python program to reverse an array so that first element becomes last.

In [22]:
Reverse = np.flip(a)
print(Reverse)

[13 12 11 10  9  8  7  6  5]


7. Write a Python program to an array converted to a float type.

In [24]:
convert = a.astype("Float64")
print(convert)

[ 5.  6.  7.  8.  9. 10. 11. 12. 13.]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  """Entry point for launching an IPython kernel.


8. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [35]:
 arr = np.array([1, 1, 1, 1,
                1, 0, 0, 1,
                1, 0, 0, 1,
                1, 1, 1, 1]).reshape(4,4)
 print(arr)


[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]
1


9. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [46]:
new_arr = np.zeros(64).astype('int32')
flag=1
while(flag<64):
  new_arr[flag]=1
  flag+=2
print(new_arr.reshape(8,8))

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


10. Write a Python program to convert a list and tuple into arrays.

In [47]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


11. Write a Python program to append values to the end of an array.

In [50]:
x = [10, 20, 30]

x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print(x.reshape(3,3))

[[10 20 30]
 [40 50 60]
 [70 80 90]]


12. Write a Python program to create an empty and a full array.

In [55]:
emp = np.empty((3,3))
full = np.full((3,3), 2)
print(emp)
print(full)

[[ 5.  6.  7.]
 [ 8.  9. 10.]
 [11. 12. 13.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


13. Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

In [70]:
cent = np.array([38, 39, 40])
farh = np.zeros((3))
for i in range(cent.size):
  farh[i] = ((9*cent[i])/5) + 32
print(farh) 

[100.4 102.2 104. ]


14. Write a Python program to find the real and imaginary parts of an array of complex numbers.

In [72]:
complex_num = np.array([-1 + 9j, 2 - 77j, 
                        31 - 25j, 40 - 311j, 
                        72 + 11j]) 
  

for i in range(len(complex_num)): 
      print("{}. complex number is {}".format(i + 1, complex_num[i])) 
      print ("The real part is: {}".format(complex_num[i].real)) 
      print ("The imaginary part is: {}\n".format(complex_num[i].imag)) 

1. complex number is (-1+9j)
The real part is: -1.0
The imaginary part is: 9.0

2. complex number is (2-77j)
The real part is: 2.0
The imaginary part is: -77.0

3. complex number is (31-25j)
The real part is: 31.0
The imaginary part is: -25.0

4. complex number is (40-311j)
The real part is: 40.0
The imaginary part is: -311.0

5. complex number is (72+11j)
The real part is: 72.0
The imaginary part is: 11.0



15. Write a Python program to test whether each element of a 1-D array is also present in a second array.

In [76]:
first = np.array([1,2,3,4,5])
second = np.array([5,9,3,2,1])
flag=0
for i in range(second.size):
  for j in range(first.size):
    if(second[i]==first[j]):
      flag+=1
      break
if(flag==second.size):
  print("Yes All element of 2nd present in 1st")
else:
  print("No all element of 1st not in 2nd")

No all element of 1st not in 2nd


16. Write a Python program to find common values between two arrays.

In [78]:
first = np.array([1,2,3,4,5])
second = np.array([5,9,3,2,1])
flag=[]
for i in range(second.size):
  for j in range(first.size):
    if(second[i]==first[j]):
      flag.append(second[i])
      break
print(flag)

[5, 3, 2, 1]


17. Write a Python program to get the unique elements of an array.

In [89]:
first = np.array([1,2,3,4,5,5,9,3,2,1])
freq = {}
flag = 0
for i in range(first.size):
  for j in range(first.size):
    if(first[i]==first[j]):
      flag += 1
  freq[first[i]] = flag
  flag=0

for m in freq:
  if(freq[m]==1):
    print(m)

  
print(freq)

4
9
{1: 2, 2: 2, 3: 2, 4: 1, 5: 2, 9: 1}


18. Write a Python program to test if all elements in an array evaluate to True.

In [7]:
bool1 = np.array([True, True])
flag = 0
for i in range(bool1.size):
  if(bool1[i]==True):
    flag+=1
if(flag==bool1.size):
  print("yes All Elements are true")
print(bool1)

yes All Elements are true
[ True  True]


19. Write a Python program to test whether any array element along a given axis evaluates to True.

In [28]:
a = np.zeros((4,4)).astype('int32')

a[2][3] = True
row = int(input("Enter the row position to be searched "))
column = int(input("Enter the column position to be searched "))
if(a[row][column]==True):
  print("Yes its a true")
else:
  print("No its a False")
print(a)

Enter the row position to be searched 2
Enter the column position to be searched 3
Yes its a true
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]


20. Write a Python program to repeat elements of an array.

In [22]:
a = np.array([1,2,3,4,5])
b = np.array([-5,-4,-3,-2,-1,0])
b = np.append(b, a)
print(b)

[-5 -4 -3 -2 -1  0  1  2  3  4  5  1  2  3  4  5  1  2  3  4  5]


21. Write a Python program to find the indices of the maximum and minimum values along the given axis of an array.

In [36]:
a = np.array([33,54,31,67,98,42,64,21,38]).reshape(3,3)
max = np.max(a)
min = np.min(a)
print("Max element is ", max)
print("Min element is ", min)

Max element is  98
Min element is  21


22. Write a Python program compare two arrays using numpy.

In [7]:
an_array = np.array([[1, 2], [3, 4]]) 
another_array = np.array([[1, 2], [3, 4]]) 
print(another_array)
  
comparison = an_array == another_array 
equal_arrays = comparison.all() 
  
print(equal_arrays) 

[[1 2]
 [3 4]]
True


23. Write a Python program to save a NumPy array to a text file.

In [14]:
an_array = np.array([1,2,3,4,5,6])
f = open("demofile1.txt", "w")
f.write(str(an_array))
f.close()
f = open("demofile1.txt", "r")
print(f.read())

[1 2 3 4 5 6]


In [13]:
#to delete a file with python
#import os
#os.remove("demofile1.txt")

24. Write a Python program to create a contiguous flattened array.

In [21]:
a = np.arange(1,28).reshape(3,3,3)
row_major_flat = np.ravel(a, order='C')
column_major_flat = np.ravel(a, order='F')
print(a_new)
print(column_major_flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[ 1 10 19  4 13 22  7 16 25  2 11 20  5 14 23  8 17 26  3 12 21  6 15 24
  9 18 27]


25.Write a program to perform addition,minimum and maximum values from a 3D array.

In [35]:
a = np.arange(1,28).reshape(3,3,3)
in_arr2 = np.arange(28,55).reshape(3,3,3)
min = np.min(a)
max = np.max(a)
add = np.add(a, in_arr2)
print("Min is {}".format(min))
print("Max is {}".format(max))
print("1st Array is \n {}".format(a))
print("2nd Array is  \n {}".format(in_arr2))
print("Added array is \n {} ".format(add))

Min is 1
Max is 27
1st Array is 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
2nd Array is  
 [[[28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]]

 [[46 47 48]
  [49 50 51]
  [52 53 54]]]
Added array is 
 [[[29 31 33]
  [35 37 39]
  [41 43 45]]

 [[47 49 51]
  [53 55 57]
  [59 61 63]]

 [[65 67 69]
  [71 73 75]
  [77 79 81]]] 
